<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('titulopagina')</title>

    <!-- Fonts -->
    <link href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {{-- <script src="https://code.jquery.com/jquery-3.6.2.min.js" integrity="sha256-2krYZKh//PcchRtd+H+VyyQoZ/e3EcrkxhM8ycwASPA=" crossorigin="anonymous"></script>
     --}}
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])

    <!-- Styles -->
    <style>
        .encabezado {
            font-size: 1.6rem;
            font-weight: 400;
            /* text-transform: uppercase; */
            text-align: center;
        }
            /*
     |-------------------------------------------------------------------
     | ANIMACION LOADER
     |-------------------------------------------------------------------
     |
     */
    .loaderp {
        background-color: rgba(0, 0, 0, 0.542);
        width: 100%;
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        position: fixed;
        z-index: 100000;
        top: 0;
        left: 0;
        clip-path: circle(150% at 100% 0%);
    }

    @keyframes ldio-ym65mg0706-o {
            0%    { opacity: 1; transform: translate(0 0) }
           49.99% { opacity: 1; transform: translate(40.8px,0) }
           50%    { opacity: 0; transform: translate(40.8px,0) }
          100%    { opacity: 0; transform: translate(0,0) }
        }
        @keyframes ldio-ym65mg0706 {
            0% { transform: translate(0,0) }
           50% { transform: translate(40.8px,0) }
          100% { transform: translate(0,0) }
        }
        .ldio-ym65mg0706 div {
          position: absolute;
          width: 40.8px;
          height: 40.8px;
          border-radius: 50%;
          top: 81.6px;
          left: 61.2px;
        }
        .ldio-ym65mg0706 div:nth-child(1) {
          background: #ffb500;
          animation: ldio-ym65mg0706 1.075268817204301s linear infinite;
          animation-delay: -0.5376344086021505s;
        }
        .ldio-ym65mg0706 div:nth-child(2) {
          background: #09326e;
          animation: ldio-ym65mg0706 1.075268817204301s linear infinite;
          animation-delay: 0s;
        }
        .ldio-ym65mg0706 div:nth-child(3) {
          background: #ffb500;
          animation: ldio-ym65mg0706-o 1.075268817204301s linear infinite;
          animation-delay: -0.5376344086021505s;
        }
        .loadingio-spinner-dual-ball-qav79bgpvnm {
          width: 204px;
          height: 204px;
          display: inline-block;
          overflow: hidden;
          background: none;
        }
        .ldio-ym65mg0706 {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(1);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-ym65mg0706 div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
    </style>

    @yield('estilos')
</head>

<body>
    <!--===ANIMACION=LOADING==========-->

<span id="loader" class="loaderp">
    <div class="loadingio-spinner-dual-ball-qav79bgpvnm"><div class="ldio-ym65mg0706">
        <div></div>
        <div></div>
        <div></div>
        </div></div>
</span>
<!--===FIN=ANIMACION=LOADING==========-->


    <div class="container-fluid">
        {{-- contenido --}}
        <div class="row">

            @include('template.partials.navbar_venta')

        </div>

        <div class="row justify-content-md-center">

            <!-- Para Mostrar Mensajes de Con la llave With 'datos'  -->
            <!-- Estilos de botones estan al Inicio -->
            @if (session('datos'))
                <div class="row justify-content-center">
                    <div class="col-8">
                        <div id="datosb" class="alert text-bg-success alert-dismissible fade show shadow p-3 my-2 rounded" role="alert">
                            {{ session('datos') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @endif
            @if (session('cancelar'))
                <div class="row justify-content-center">
                    <div class="col-8">
                        <div id="cancelarb" class="alert text-bg-warning alert-dismissible fade show shadow p-3 my-2 rounded" role="alert">
                            {{ session('cancelar') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                        </div>
                    </div>
                </div>
            @endif
            <!-- Para Mostrar Mensajes de errores de las Validaciones en Laravel en los controladores  -->

            @if ($errors->any())
                <div class="row justify-content-center">
                    <div class="col-8">
                        <div id="cancelarb" class="alert text-bg-danger alert-dismissible fade show shadow p-3 my-2 rounded" role="alert">
                            <h4 class="alert-heading">Verifique lo siguiente:</h4>
                            <ul>
                                @foreach ($errors->all() as $error )
                                        {{ $error }}
                                @endforeach
                            </ul>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                        </div>
                    </div>
                </div>
            @endif



                @yield('contenido')
                {{-- /contenido --}}

        </div>
        {{-- /contenido --}}

    </div>




   
     <script type="module">
    
        $(document).ready(function () {
            window.setTimeout(function() {
                $(".alert").fadeOut(1500).slideUp(1000, function(){
                    $(this).remove();
                });
            },10000);

           /*  document.querySelector('#loader').setAttribute('hidden',true); */
        });
    </script>
    <!-- Fontawesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    

       <!-- Include: Typeahaed --->
       {{-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script> --}}
       {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-3-typeahead/4.0.2/bootstrap3-typeahead.min.js"> --}}
    
     @yield('scripts')
</body>

</html>
